#!/bin/bash

# $1 - the code file

count=0;
lineNum=0;
linesInFunc=0;
flag=0;
func="";
func_start=0
while read -a line; do
	let lineNum+=1;
	if [[ "${line[*]}" = *"{"* ]]; then
		let count+=1;
		if (( $count==1 )); then
			func_start=$lineNum
			if [[ "$line" = "static" ]]; then
				func=${line[2]}
			else
				func=${line[1]}
			fi
		fi
	elif [[ "${line[*]}" = *"}"* ]]; then
		let count-=1;
	fi
	if (( $count > 0 )); then
		let linesInFunc+=1;
	elif (( $count == 0 )); then
		if (( $linesInFunc > 30 )); then
			echo func $func is longer then allowed in $func_start
			flag=1;	
		fi
		linesInFunc=0;
	fi
done < $1

if (( $flag==0 )); then
	echo OK
fi
#end
